# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
timezone: UTC
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-postcss

# jekyll-seo-tag configuration
title: "FinOps Foundation - Collaborative, Real-Time Cloud Financial Management"
description: "Delivering expertise, and inspiration for and by FinOps leaders and practitioners â€” all aimed at helping members become better at cloud financial management."

collections:
  stories:
    output: true
  links:
    output: true
  tools-services:
    output: true
  domains:
    output: true
  capabilities:
    output: true

defaults:
  - scope:
      path: "_pages/framework"
      type: "pages"
    values:
      identifier: "framework"
  - scope:
      path: ""
      type: "domains"
    values:
      identifier: "framework"
  - scope:
      path: ""
      type: "capabilities"
    values:
      identifier: "framework"
  - scope:
      path: "_pages/projects"
      type: "pages"
    values:
      identifier: "projects"
  - scope:
      path: "_pages/introduction"
      type: "pages"
    values:
      identifier: "introduction"
  - scope:
      path: "_pages/resources"
      type: "pages"
    values:
      identifier: "resources"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - yarn-error.log
  - .jekyll-cache/
  - netlify.toml
  - .gitignore

permalink: pretty

include:
  - _redirects
  - _pages/